#ifndef RESOURCE_H
#define RESOURCE_H

#include "common.h"

#define IDB_SNAKE_FOOD_TILE1  100
#define IDB_SNAKE_FOOD_TILE2  101
#define IDB_SNAKE_FOOD_TILE3  102
#define IDB_SNAKE_FOOD_TILE4  103
#define IDB_SNAKE_FOOD_TILE5  104
#define IDB_SNAKE_FOOD_TILE6  105
#define IDB_SNAKE_FOOD_TILE7  106
#define IDB_SNAKE_FOOD_TILE8  107
#define IDB_SNAKE_FOOD_TILE9  108


#define IDW_SOUND_EAT       110
#define IDW_SOUND_GAME_OVER 111
#define IDW_SOUND_WIN       112

#define VERSION_STR "1.0.2"
#define VERSION_SEQ 1,0,2

#endif
